FROM python:3.8-slim-buster

WORKDIR /app

EXPOSE 8000

COPY ./requirements/api.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./entry.py ./entry.py
COPY ./collection ./collection

CMD [ "python3", "entry.py"]
