FROM python:3.8-slim-buster

RUN apt-get -y update
RUN apt-get -y install git

WORKDIR /app

COPY ./requirements/cron.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./cron.py ./cron.py
COPY ./collection ./collection

CMD [ "huey_consumer.py", "cron.huey", "-v"]
